variable "key_name" {}
variable "count_instance" {}
variable "instance_type" {}
variable "ami_owners" {}
variable "ami_values" {}
variable "vpc_id" {}
variable "subnet_id" {}
variable "network_interface_id" {}
variable "private_ip" {}
