variable "key_name" {}
variable "count_instance" {}
variable "instance_type" {}
variable "ami_owners" {}
variable "ami_values" {}
variable "subnet_id" {}
variable "private_ip" {}
variable "instance_name" {}
variable "ec2_security_group_id" {}
